### ISSUE TITLE
use pagemenu in tabbar

### ISSUE THREAD

**Issue by chenenyu** [uacaps/PageMenu#18]
When i try to use some pagemenus in a viewcontroller within tabbar, the barItem won't show correctly...

**Comment by fahlout** [comment]
I haven't had any problems with using a tab bar controller so far. I would need to your code in order to figure out what's going on.

**Comment by MatthewYork** [comment]
Resolved as of 2.0.0

**Comment by htarwara6245** [comment]
Still not resolved...Items at the end of UITableView still not fully shown and its hidden under tabbar.

Worst sometime, view can't scroll.
